# Creating Tensors

In [1]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y

print(z)
print(z.size())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

x = torch.tensor([[1, 2, 3], [4, 5, 6]], device=device)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], device=device)
z = x + y

print(z)
print(z.shape)
print(z.device)

cuda
tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
torch.Size([2, 3])
cuda:0


In [3]:
import numpy as np

# Created tensors from preexisting arrays
w = torch.tensor([1, 2, 3])
w = torch.tensor((1, 2, 3))
w = torch.tensor(np.array([1, 2, 3]))

# Initalized by size
w = torch.empty(100, 200)
w = torch.zeros(100, 200)
w = torch.ones(100, 200)

In [4]:
# Initialize by size with random values
w = torch.rand(100, 200)
w = torch.randn(100, 200)
w = torch.randint(5, 12, (100, 200))

# Initialized by certain datatype or device
w = torch.empty((100, 200), dtype=torch.float64, device=device)

# Initialized to have same size, datatpe and device as a tensor
x = torch.empty_like(w)
x = torch.zeros_like(w)
x = torch.ones_like(w)

In [5]:
w = torch.arange(1, 10, 1)
print(w)
w = torch.linspace(1, 10, 10)
print(w)
w = torch.logspace(1, 10, 10)
print(w)
w = torch.eye(3, 2)
print(w)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05, 1.0000e+06,
        1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])


In [6]:
print(w.numpy(), type(w.numpy()))
print(w.tolist(), type(w.tolist()))

[[1. 0.]
 [0. 1.]
 [0. 0.]] <class 'numpy.ndarray'>
[[1.0, 0.0], [0.0, 1.0], [0.0, 0.0]] <class 'list'>


In [7]:
x.dtype
x.device
x.shape
x.ndim
x.requires_grad
x.grad
x.grad_fn

x.cuda
x.is_sparse
x.is_quantized
x.is_leaf
x.is_mkldnn

x.layout

torch.strided

In [8]:
w = torch.tensor([1, 2, 3], dtype=torch.float64)

w.int()
print(w)
w = w.int()
print(w)

w = w.to(torch.float32)
print(w.dtype)
w = w.to(dtype=torch.int32)
print(w.dtype)

x = torch.tensor([1, 2, 3], dtype=torch.int32)
y = torch.tensor([1, 2, 3], dtype=torch.float32)
z = x + y
print(z.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int32)
torch.float32
torch.int32
torch.float32


In [9]:
torch.rand(3, 2)
torch.randn(3, 2)
torch.normal(0, 1, (3, 2))
torch.randint(1, 10, (3, 2))
torch.randperm(10)
torch.bernoulli(torch.tensor([0.1, 0.2, 0.8, 0.9]))
torch.multinomial(torch.tensor([0.1, 0.2, 0.8, 0.9]), 2)

tensor([2, 3])

In [10]:
x = torch.empty(3, 2).log_normal_()
x

tensor([[98.1737, 18.2089],
        [18.3097,  3.6761],
        [ 0.1494,  1.2581]])

In [11]:
torch.empty_like(x)
torch.zeros_like(x)
torch.ones_like(x)
torch.full_like(x, 10)
torch.rand_like(x)
torch.randn_like(x)
torch.randint_like(x, 1, 10)

tensor([[6., 3.],
        [1., 5.],
        [8., 1.]])

# Tensor Operations

## Indexing, Slicing, Combining, and Splitting Tensors

In [12]:
x = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x)

# Indexing
print(x[1, 1])
print(x[1, 1].item())

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor(4)
4


In [13]:
# Slicing
print(x[:2, 1])

# Boolean Indexing
print(x[x < 5])

tensor([2, 4])
tensor([1, 2, 3, 4])


In [14]:
print(x.T)
print(x.t())
print(x.transpose(0, 1))

# Change shape
print(x.view((2, 4)))

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [15]:
# Combining Tensors
y = torch.stack((x, x))
print(y)
print(y.shape)

a, b = y.unbind(dim=0)
print(a)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
torch.Size([2, 4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [16]:
torch.cat((x, x), dim=0)
torch.chunk(x, 4, dim=0)
torch.gather(x, dim=0, index=torch.tensor([[1, 1], [1, 1], [2, 2], [3, 3]]))
torch.index_select(x, dim=0, index=torch.tensor([1, 1, 2, 3]))
torch.masked_select(x, torch.BoolTensor([[1, 1], [0, 1], [0, 1], [0, 1]]))
torch.narrow(x, dim=0, start=0, length=2)
torch.nonzero(x)
torch.reshape(x, shape=(2, 4))
torch.split(x, split_size_or_sections=2, dim=0)
x = torch.unsqueeze(x, dim=0)
x = torch.squeeze(x)
torch.take(x, index=torch.tensor([0, 1, 2, 3]))
torch.where(x > 5, x, x * 2)

tensor([[ 2,  4],
        [ 6,  8],
        [10,  6],
        [ 7,  8]])

## Tensor Operations for Mathematics

### Pointwise

In [17]:
# Basic Math
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

x.add(y)
print(x)
x.add_(y)
print(x)

x.sub(y)
x.div(y)
x.mul(y)
x.reciprocal()
x.true_divide(y)

tensor([[1, 2],
        [3, 4]])
tensor([[ 6,  8],
        [10, 12]])


tensor([[1.2000, 1.3333],
        [1.4286, 1.5000]])

In [18]:
# Truncation

x.ceil()
x.clamp(min=2, max=5)
x.floor()
x.floor_divide(y)
x.fmod(y)
x.remainder(y)
x.round()
x.sigmoid()

tensor([[0.9975, 0.9997],
        [1.0000, 1.0000]])

In [19]:
# Complex numbers
x = torch.tensor([1 + 2j, 3 + 4j])

x.abs()
x.angle()
x.conj()
x.imag
x.real

tensor([1., 3.])

In [20]:
# Trigonometry
x = torch.tensor([0, torch.pi / 4, torch.pi / 2, 3 * torch.pi / 4])

x.acos()
x.asin()
x.atan()
x.sin()
x.cos()
x.sinh()
x.cosh()
x.tan()
x.tanh()
x.deg2rad()
x.rad2deg()

tensor([  0.,  45.,  90., 135.])

In [21]:
# Exponents and logarithms

x = torch.tensor([1, 2, 3])

x.exp()
x.expm1()
x.log()
x.log10()
x.log1p()
x.log2()
x.pow(2)
x.rsqrt()
x.sqrt()
x.square()

tensor([1, 4, 9])

In [22]:
# Logical
x = torch.tensor([[1, 0], [0, 1]])
y = torch.tensor([[0, 1], [1, 0]])

x.logical_and(y)
x.logical_not()
x.logical_or(y)
x.logical_xor(y)

tensor([[True, True],
        [True, True]])

In [23]:
# Bitwise operators

x.bitwise_not()
x.bitwise_and(y)
x.bitwise_or(y)
x.bitwise_xor(y)

tensor([[1, 1],
        [1, 1]])

In [24]:
# Error functions

x = torch.tensor([0.0, 0.5, 1.0])

x.erf()
x.erfc()
x.erfinv()

tensor([0.0000, 0.4769,    inf])

In [25]:
# Gamma functions

x = torch.tensor([1, 2, 3])

x.digamma()
x.lgamma()
x.mvlgamma(p=2)
x.polygamma(n=2)

tensor([-2.4041, -0.4041, -0.1541])

### Reduction operations

In [26]:
x = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])
y = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])

torch.argmax(x, dim=0)
torch.argmin(x, dim=0)
torch.dist(x, y, p=3.5)
torch.logsumexp(x, dim=0)
torch.mean(x, dim=0)
torch.median(x, dim=0)
torch.mode(x, dim=0)
torch.norm(x, p=2, dim=0)
torch.prod(x, dim=0)
torch.std(x, dim=0)
torch.std_mean(x, dim=0)
torch.sum(x, dim=0)
torch.var(x, dim=0)
torch.var_mean(x, dim=0)
torch.unique(x, dim=0)
torch.unique_consecutive(x, dim=0)

tensor([[0.1000, 0.2000, 0.3000],
        [0.9000, 0.5000, 0.6000],
        [0.7000, 0.0000, 0.9000]])

### Comparison Operations

In [27]:
# Compare a tensor to other tensors

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

x.eq(y)
x == y
x.ge(y)
x >= y
x.gt(y)
x > y
x.le(y)
x <= y
x.lt(y)
x < y
x.ne(y)
x != y


x.isclose(y, atol=1e-08, rtol=1e-08)
x.isfinite()
x.isinf()
x.isnan()

x.allclose(y)
x.equal(y)

x.argsort(dim=0)
x.kthvalue(k=2, dim=0)
x.max(dim=0)
x.min(dim=0)
x.sort(dim=0, descending=True)
x.topk(k=2, dim=0)

torch.return_types.topk(
values=tensor([[3, 4],
        [1, 2]]),
indices=tensor([[1, 1],
        [0, 0]]))

### Linear algebra operations

In [28]:
x = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])
y = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])

torch.matmul(x, y)
torch.mm(x, y)
torch.chain_matmul(x, y, x)
torch.bmm(torch.stack((x, x)), torch.stack((y, y)))
torch.addmm(x, y, x)
torch.mv(x, y[:, 0])
torch.addmv(x[:, 0], y, x[:, 0])
torch.matrix_exp(x)
torch.matrix_power(x, 2)
torch.linalg.eig(x)
torch.inverse(x)
torch.det(x)
torch.logdet(x)
torch.dot(x[0, :], y[:, 0])
torch.linalg.solve(x, y)
torch.svd(x)
torch.pca_lowrank(x, q=2)

/usr/local/lib/python3.10/dist-packages/torch/functional.py:1822: UserWarning: torch.chain_matmul is deprecated and will be removed in a future PyTorch release. Use torch.linalg.multi_dot instead, which accepts a list of two or more tensors rather than multiple parameters. (Triggered internally at ../aten/src/ATen/native/LinearAlgebra.cpp:1104.)
  return _VF.chain_matmul(matrices)  # type: ignore[attr-defined]


(tensor([[-0.8149, -0.0514],
         [ 0.4520, -0.6800],
         [ 0.3629,  0.7314]]),
 tensor([0.6815, 0.4346]),
 tensor([[ 0.8501, -0.2419],
         [ 0.0925, -0.8059],
         [ 0.5185,  0.5404]]))

### Spectral and other math operations

In [29]:
# Fourier
x = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])

torch.fft.fft(x)
torch.fft.ifft(x)
torch.fft.rfft(x)
torch.fft.irfft(x)

tensor([[ 0.2000, -0.0500,  0.0000, -0.0500],
        [ 0.6250,  0.0750,  0.1250,  0.0750],
        [ 0.4000, -0.0500,  0.4000, -0.0500]])

In [30]:
# Histogram and bin counts

torch.histc(x, bins=2, min=0, max=1)
torch.histogram(x, bins=2, range=(0, 1))

x = torch.tensor([0, 1, 2, 3, 4])
torch.bincount(x, minlength=2)

tensor([1, 1, 1, 1, 1])

In [31]:
# Cumulative operations
x = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])

torch.cummax(x, dim=0)
torch.cummin(x, dim=0)
torch.cumprod(x, dim=0)
torch.cumsum(x, dim=0)
torch.trace(x)
torch.einsum("ij,jk->ik", x, x)

tensor([[0.4000, 0.1200, 0.4200],
        [0.9600, 0.4300, 1.1100],
        [0.7000, 0.1400, 1.0200]])

In [32]:
# Normalization functions
x = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])

torch.cdist(x, x)
torch.renorm(x, p=2, dim=0, maxnorm=1)

tensor([[0.1000, 0.2000, 0.3000],
        [0.7553, 0.4196, 0.5035],
        [0.6139, 0.0000, 0.7894]])

In [33]:
# Cross product, dot product, and Cartesian product

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

torch.cross(x, y)
torch.dot(x, y)
torch.cartesian_prod(x, y)

<ipython-input-33-7904286dd507>:6: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:62.)
  torch.cross(x,y)


tensor([[1, 4],
        [1, 5],
        [1, 6],
        [2, 4],
        [2, 5],
        [2, 6],
        [3, 4],
        [3, 5],
        [3, 6]])

In [34]:
# Functions that create a diagonal tensor with elements of the input tensor

torch.diag(x)
torch.diag_embed(x)
torch.diagflat(x)

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [35]:
# Matrix reduction and restructuring functions

x = torch.tensor([[0.1, 0.2, 0.3], [0.9, 0.5, 0.6], [0.7, 0.0, 0.9]])

torch.flatten(x)
torch.flip(x, dims=(0, 1))
torch.rot90(x, k=1, dims=(0, 1))
torch.repeat_interleave(x, repeats=2, dim=0)
torch.meshgrid(x[:, 0], x[:, 0])
torch.roll(x, shifts=1, dims=0)
torch.combinations(x[:, 0], r=2)

/usr/local/lib/python3.10/dist-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


tensor([[0.1000, 0.9000],
        [0.1000, 0.7000],
        [0.9000, 0.7000]])

In [36]:
# Functions that return the lower or upper triangles and their indices

torch.tril(x)
torch.tril_indices(3, 3)
torch.triu(x)
torch.triu_indices(3, 3)

tensor([[0, 0, 0, 1, 1, 2],
        [0, 1, 2, 1, 2, 2]])

## Automatic Differentiation (Autograd)

In [37]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float, requires_grad=True)

f = x.pow(2).sum()

f.backward()

print(x.grad)

tensor([[2., 4.],
        [6., 8.]])
