# Creating Tensors

In [1]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y

print(z)
print(z.size())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

x = torch.tensor([[1, 2, 3], [4, 5, 6]], device=device)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], device=device)
z = x + y

print(z)
print(z.shape)
print(z.device)

cuda
tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
torch.Size([2, 3])
cuda:0


In [3]:
import numpy as np

# Created tensors from preexisting arrays
w = torch.tensor([1, 2, 3])
w = torch.tensor((1, 2, 3))
w = torch.tensor(np.array([1, 2, 3]))

# Initalized by size
w = torch.empty(100, 200)
w = torch.zeros(100, 200)
w = torch.ones(100, 200)

In [4]:
# Initialize by size with random values
w = torch.rand(100, 200)
w = torch.randn(100, 200)
w = torch.randint(5, 12, (100, 200))

# Initialized by certain datatype or device
w = torch.empty((100, 200), dtype=torch.float64, device=device)

# Initialized to have same size, datatpe and device as a tensor
x = torch.empty_like(w)
x = torch.zeros_like(w)
x = torch.ones_like(w)

In [8]:
w = torch.arange(1, 10, 1)
print(w)
w = torch.linspace(1, 10, 10)
print(w)
w = torch.logspace(1, 10, 10)
print(w)
w = torch.eye(3, 2)
print(w)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05, 1.0000e+06,
        1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])


In [14]:
print(w.numpy(), type(w.numpy()))
print(w.tolist(), type(w.tolist()))

[[1. 0.]
 [0. 1.]
 [0. 0.]] <class 'numpy.ndarray'>
[[1.0, 0.0], [0.0, 1.0], [0.0, 0.0]] <class 'list'>


In [17]:
x.dtype
x.device
x.shape
x.ndim
x.requires_grad
x.grad
x.grad_fn

x.cuda
x.is_sparse
x.is_quantized
x.is_leaf
x.is_mkldnn

x.layout

torch.strided

In [28]:
w = torch.tensor([1, 2, 3], dtype=torch.float64)

w.int()
print(w)
w = w.int()
print(w)

w = w.to(torch.float32)
print(w.dtype)
w = w.to(dtype=torch.int32)
print(w.dtype)

x = torch.tensor([1, 2, 3], dtype=torch.int32)
y = torch.tensor([1, 2, 3], dtype=torch.float32)
z = x + y
print(z.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int32)
torch.float32
torch.int32
torch.float32


In [45]:
torch.rand(3, 2)
torch.randn(3, 2)
torch.normal(0, 1, (3, 2))
torch.randint(1, 10, (3, 2))
torch.randperm(10)
torch.bernoulli(torch.tensor([0.1, 0.2, 0.8, 0.9]))
torch.multinomial(torch.tensor([0.1, 0.2, 0.8, 0.9]), 2)

tensor([2, 3])

In [51]:
x = torch.empty(3, 2).log_normal_()
x

tensor([[15.5731,  3.6439],
        [ 0.3014,  5.3849],
        [ 5.2020, 57.6354]])

In [56]:
torch.empty_like(x)
torch.zeros_like(x)
torch.ones_like(x)
torch.full_like(x, 10)
torch.rand_like(x)
torch.randn_like(x)
torch.randint_like(x, 1, 10)

tensor([[3., 2.],
        [2., 3.],
        [7., 8.]])

# Tensor Operations

## Indexing, Slicing, Combining, and Splitting Tensors

In [58]:
x = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x)

# Indexing
print(x[1, 1])
print(x[1, 1].item())

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor(4)
4


In [59]:
# Slicing
print(x[:2, 1])

# Boolean Indexing
print(x[x < 5])

tensor([2, 4])
tensor([1, 2, 3, 4])


In [100]:
print(x.T)
print(x.t())
print(x.transpose(0, 1))

# Change shape
print(x.view((2, 4)))

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [65]:
# Combining Tensors
y = torch.stack((x, x))
print(y)
print(y.shape)

a, b = y.unbind(dim=0)
print(a)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
torch.Size([2, 4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [98]:
torch.cat((x, x), dim=0)
torch.chunk(x, 4, dim=0)
torch.gather(x, dim=0, index=torch.tensor([[1, 1], [1, 1], [2, 2], [3, 3]]))
torch.index_select(x, dim=0, index=torch.tensor([1, 1, 2, 3]))
torch.masked_select(x, torch.BoolTensor([[1, 1], [0, 1], [0, 1], [0, 1]]))
torch.narrow(x, dim=0, start=0, length=2)
torch.nonzero(x)
torch.reshape(x, shape=(2, 4))
torch.split(x, split_size_or_sections=2, dim=0)
x = torch.unsqueeze(x, dim=0)
x = torch.squeeze(x)
torch.take(x, index=torch.tensor([0, 1, 2, 3]))
torch.where(x > 5, x, x * 2)

tensor([[ 2,  4],
        [ 6,  8],
        [10,  6],
        [ 7,  8]])

## Tensor Operations for Mathematics